version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10.15
    description: Run the unit tests
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Jest tests
          command: yarn test
      - store_artifacts:
          path: coverage
